import { User, UserRole, UserStatus } from '@/types/dashboard'

const roles: UserRole[] = ['Admin', 'User', 'Editor', 'Manager']
const statuses: UserStatus[] = [
  'Active',
  'Active',
  'Active',
  'Inactive',
  'Pending',
  'Blocked'
]

const firstNames = [
  'Alice',
  'Bob',
  'Charlie',
  'Diana',
  'Evan',
  'Fiona',
  'George',
  'Hannah',
  'Ivan',
  'Julia',
  'Kevin',
  'Laura',
  'Mike',
  'Nina',
  'Oscar',
  'Paula',
  'Quinn',
  'Rachel',
  'Steve',
  'Tina',
  'Umar',
  'Vera',
  'Will',
  'Xena',
  'Yusuf',
  'Zara',
  'Aaron',
  'Bella',
  'Carlos',
  'Daisy',
  'Eliot',
  'Faith',
  'Gavin',
  'Heidi',
  'Ian',
  'Jasmine',
  'Kyle',
  'Luna',
  'Mason',
  'Nora',
  'Owen',
  'Priya',
  'Rory',
  'Sara',
  'Tom',
  'Uma',
  'Victor',
  'Wendy',
  'Xander',
  'Yasmin',
  'Zack',
  'Amy',
  'Brian',
  'Chloe',
  'Derek',
  'Ellie',
  'Felix',
  'Grace',
  'Henry',
  'Isla',
  'Jack',
  'Kira',
  'Liam',
  'Mia',
  'Nathan',
  'Olive',
  'Peter',
  'Quinn',
  'Rose',
  'Sam',
  'Taylor',
  'Ursula'
]

const lastNames = [
  'Freeman',
  'Smith',
  'Davis',
  'Prince',
  'Wright',
  'Clarke',
  'Evans',
  'Martin',
  'Thompson',
  'Garcia',
  'Martinez',
  'Robinson',
  'Clark',
  'Lewis',
  'Lee',
  'Walker',
  'Hall',
  'Allen',
  'Young',
  'King',
  'Scott',
  'Green',
  'Baker',
  'Nelson',
  'Carter',
  'Mitchell',
  'Perez',
  'Roberts',
  'Turner',
  'Phillips',
  'Campbell',
  'Parker',
  'Edwards',
  'Collins',
  'Stewart',
  'Morris',
  'Rogers',
  'Reed',
  'Cook',
  'Morgan',
  'Bell',
  'Murphy',
  'Bailey',
  'Rivera',
  'Cooper',
  'Richardson',
  'Cox',
  'Ward',
  'Torres',
  'Peterson',
  'Gray',
  'Ramirez',
  'James',
  'Watson',
  'Brooks',
  'Kelly',
  'Sanders',
  'Price',
  'Bennett',
  'Wood',
  'Barnes',
  'Ross',
  'Henderson',
  'Coleman',
  'Jenkins',
  'Perry',
  'Powell',
  'Long',
  'Patterson',
  'Hughes',
  'Flores'
]

function generateMockUsers(count: number): User[] {
  return Array.from({ length: count }, (_, i) => {
    const firstName = firstNames[i % firstNames.length]
    const lastName = lastNames[i % lastNames.length]
    const name = `${firstName} ${lastName}`
    const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`
    const role = roles[i % roles.length]
    const status = statuses[i % statuses.length]
    const daysAgo = Math.floor(Math.random() * 30)
    const lastLogin = new Date(Date.now() - daysAgo * 86_400_000).toISOString()

    return {
      id: `usr_${String(i + 1).padStart(2, '0')}`,
      name,
      email,
      role,
      status,
      lastLogin
    }
  })
}

export const MOCK_USERS: User[] = generateMockUsers(70)
